enable_pairing:
  description: Enable pairing of MAX! devices for a given duration
  fields:
    device_path:
      name: Device Path
      description: The path of the CUL device for which pairing shall be enabled
      default: &default "COM1 or /dev/ttyUSB0 or 192.168.0.1:2323"
      example: *default 
      selector:
        text:
    duration:
      name: Duration
      description: Duration for which pairing is possible in seconds
      default: 60
      selector:
        number:
          min: 0
          max: 300
          unit_of_measurement: seconds
